name: check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  secrets-scan:
    uses: rechenmaschine-playground/ci-templates/.github/workflows/secrets-scan.yml@9ccb2bf4e790fd595896977585708d61673b71d5 # v0.1.0
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
